FROM ubuntu:16.04

USER root

RUN apt-get update
RUN apt-get -qq update
RUN apt-get install -y build-essential
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs


EXPOSE 3000

ENV NODE_ENV development
RUN mkdir /app
WORKDIR /app


# add package.json and run npm install before adding the rest of the files
# this way, you only run npm install when package.json changes
ADD /web-server/package.json /app/package.json

# add the rest of the files
ADD web-server /app

RUN apk add --no-cache make gcc g++ python

RUN npm install -gq mocha
RUN npm install -q

# add the rest of the files
ADD . /app

CMD mocha "web-server/test/**/*.js" --timeout 20000

# to run test on cli
# docker-compose -f docker-compose.test.yml -p ci up --build
