path:
  data: /data/data
  logs: /data/log

# Cluster information
cluster.name: real-affinities
node.name: real-affinities

# Security settings
# script.disable_dynamic: true

# Index settings
# action.auto_create_index: false

# Turn off swap to get a big speed increase.  This will prevent the ES server
# from swapping memory on the node. https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html#setup-configuration-memory
# bootstrap.mlockall: true

# Disable deleting all indices from the api.
# action.disable_delete_all_indices: true

# indices.cluster.send_refresh_mapping: false

# log4j.shutdownHookEnabled: false
# log4j2.disable.jmx: true
# log4j.skipJansi: true
