version: "3.3"
services:
  web:
    env_file: accounts.env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities-test
      - MYSQL_USER=development
      - MYSQL_PASSWORD=development
    ports:
      - 3307:3307
  migrations:
    image: micheleminno/db-migrations:latest
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
