version: "3.3"
services:
  web:
    env_file: accounts.env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 30:3000
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities-test
      - MYSQL_USER=development
      - MYSQL_PASSWORD=development
    ports:
      - 33:3306
  migrations:
    image: micheleminno/db-migrations:latest
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
