version: "3.3"
services:
  web:
    env_file: accounts.env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities
      - MYSQL_USER=production
      - MYSQL_PASSWORD=production
    ports:
      - 3306:3306
  migrations:
    image: micheleminno/db-migrations:latest
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
