FROM node:6.11-alpine

EXPOSE 3000
ENV NODE_ENV development
RUN mkdir /app
WORKDIR /app

# add package.json and run npm install before adding the rest of the files
# this way, you only run npm install when package.json changes
ADD /web-server/package.json /app/package.json

RUN apk add --no-cache make gcc g++ python

RUN npm install -g mocha
RUN npm install
