version: "3.3"
services:
  web:
    image: micheleminno/real-affinities:latest
    env_file:
      - accounts.env
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon web-server/server/Server.js
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities
      - MYSQL_USER=production
      - MYSQL_PASSWORD=production
    ports:
      - 3306:3306
  migrations:
    image: micheleminno/db-migrations:latest
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
  fixtures:
    image: micheleminno/db-fixtures:latest
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
