version: 2

jobs:
  build:
    working_directory: ~
    docker:
      - image: micheleminno/real-affinities

    steps:
      - checkout
      - run: npm test

      
# machine:
#   services:
#     - docker
#
# dependencies:
#   override:
#     - docker build -t micheleminno/real-affinities .
#
# test:
#   override:
#     - docker run micheleminno/real-affinities npm test
#
# deployment:
#   production:
#     branch: master
#     commands:
#       - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#       - ./deploy.sh
