version: 2

jobs:
  build:
    working_directory: ~
    docker:
      - image: mysql:5.5
        environment:
        - MYSQL_ROOT_PASSWORD: password
        - MYSQL_DATABASE: real-affinities-test
        - MYSQL_USER: development
        - MYSQL_PASSWORD: development
      - image: micheleminno/db-migrations
        environment:
          - NODE_ENV: development
    steps:
      - checkout
      - run:
          name: Build real-affinities
          command: docker build -t micheleminno/real-affinities .
    test:
      docker:
      - image: real-affinities
    steps:
      - checkout
      - run:
          name: Test real-affinities
          command: docker run micheleminno/real-affinities npm test

# deployment:
#   production:
#     branch: master
#     commands:
#       - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#       - ./deploy.sh
